"""005 normalization of models users, points_transactions and pushup_entries

Revision ID: 6b48ef77dd4b
Revises: 06496c3e82a6
Create Date: 2025-06-20 18:26:57.661675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b48ef77dd4b'
down_revision: Union[str, None] = '06496c3e82a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('points_transactions', sa.Column('balance_after', sa.Integer(), nullable=False, server_default="0"))
    op.add_column('pushup_entries', sa.Column('streak', sa.SmallInteger(), nullable=False, server_default="0"))
    op.drop_column('users', 'streak')
    op.drop_column('users', 'points')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('points', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('streak', sa.SMALLINT(), autoincrement=False, nullable=False))
    op.drop_column('pushup_entries', 'streak')
    op.drop_column('points_transactions', 'balance_after')
    # ### end Alembic commands ###
